---
name: continuous-integration
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test-package:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - python-version: '3.12'
                      aiida-core: 'aiida-core==2.8.0'
                    - python-version: '3.12'
                      aiida-core: 'aiida-core>=2.8,<3'
                    - python-version: '3.13'
                      aiida-core: 'aiida-core>=2.8,<3'
        steps:

            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install the package and dependencies
              run: pip install -e .[dev] "${{ matrix.aiida-core }}"

            - name: Run pytest
              run: pytest --cov --cov-branch --cov-report=xml

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
